sonar.organization=Lime556
sonar.projectKey=sopra-fs26-group-11-client

# relative paths to source directories. More details and properties are described
# at https://docs.sonarsource.com/sonarqube-cloud/advanced-setup/analysis-scope/
sonar.sources=./src